/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CHandleRouteImport } from './routes/c.$handle'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated.feed'
import { Route as AuthenticatedEstudioRouteImport } from './routes/_authenticated.estudio'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated.configuracoes'
import { Route as AuthenticatedCarteiraRouteImport } from './routes/_authenticated.carteira'
import { Route as AuthenticatedAssinaturasRouteImport } from './routes/_authenticated.assinaturas'
import { Route as AuthenticatedMensagensIndexRouteImport } from './routes/_authenticated.mensagens.index'
import { Route as AuthenticatedEstudioIndexRouteImport } from './routes/_authenticated.estudio.index'
import { Route as AuthenticatedMensagensConversationIdRouteImport } from './routes/_authenticated.mensagens.$conversationId'
import { Route as AuthenticatedEstudioTiersRouteImport } from './routes/_authenticated.estudio.tiers'
import { Route as AuthenticatedEstudioPostsRouteImport } from './routes/_authenticated.estudio.posts'

const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CHandleRoute = CHandleRouteImport.update({
  id: '/c/$handle',
  path: '/c/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEstudioRoute = AuthenticatedEstudioRouteImport.update({
  id: '/estudio',
  path: '/estudio',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCarteiraRoute = AuthenticatedCarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssinaturasRoute =
  AuthenticatedAssinaturasRouteImport.update({
    id: '/assinaturas',
    path: '/assinaturas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMensagensIndexRoute =
  AuthenticatedMensagensIndexRouteImport.update({
    id: '/mensagens/',
    path: '/mensagens/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEstudioIndexRoute =
  AuthenticatedEstudioIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEstudioRoute,
  } as any)
const AuthenticatedMensagensConversationIdRoute =
  AuthenticatedMensagensConversationIdRouteImport.update({
    id: '/mensagens/$conversationId',
    path: '/mensagens/$conversationId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEstudioTiersRoute =
  AuthenticatedEstudioTiersRouteImport.update({
    id: '/tiers',
    path: '/tiers',
    getParentRoute: () => AuthenticatedEstudioRoute,
  } as any)
const AuthenticatedEstudioPostsRoute =
  AuthenticatedEstudioPostsRouteImport.update({
    id: '/posts',
    path: '/posts',
    getParentRoute: () => AuthenticatedEstudioRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explorar': typeof ExplorarRoute
  '/assinaturas': typeof AuthenticatedAssinaturasRoute
  '/carteira': typeof AuthenticatedCarteiraRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/estudio': typeof AuthenticatedEstudioRouteWithChildren
  '/feed': typeof AuthenticatedFeedRoute
  '/c/$handle': typeof CHandleRoute
  '/estudio/posts': typeof AuthenticatedEstudioPostsRoute
  '/estudio/tiers': typeof AuthenticatedEstudioTiersRoute
  '/mensagens/$conversationId': typeof AuthenticatedMensagensConversationIdRoute
  '/estudio/': typeof AuthenticatedEstudioIndexRoute
  '/mensagens/': typeof AuthenticatedMensagensIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explorar': typeof ExplorarRoute
  '/assinaturas': typeof AuthenticatedAssinaturasRoute
  '/carteira': typeof AuthenticatedCarteiraRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/c/$handle': typeof CHandleRoute
  '/estudio/posts': typeof AuthenticatedEstudioPostsRoute
  '/estudio/tiers': typeof AuthenticatedEstudioTiersRoute
  '/mensagens/$conversationId': typeof AuthenticatedMensagensConversationIdRoute
  '/estudio': typeof AuthenticatedEstudioIndexRoute
  '/mensagens': typeof AuthenticatedMensagensIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/explorar': typeof ExplorarRoute
  '/_authenticated/assinaturas': typeof AuthenticatedAssinaturasRoute
  '/_authenticated/carteira': typeof AuthenticatedCarteiraRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/estudio': typeof AuthenticatedEstudioRouteWithChildren
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/c/$handle': typeof CHandleRoute
  '/_authenticated/estudio/posts': typeof AuthenticatedEstudioPostsRoute
  '/_authenticated/estudio/tiers': typeof AuthenticatedEstudioTiersRoute
  '/_authenticated/mensagens/$conversationId': typeof AuthenticatedMensagensConversationIdRoute
  '/_authenticated/estudio/': typeof AuthenticatedEstudioIndexRoute
  '/_authenticated/mensagens/': typeof AuthenticatedMensagensIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/explorar'
    | '/assinaturas'
    | '/carteira'
    | '/configuracoes'
    | '/estudio'
    | '/feed'
    | '/c/$handle'
    | '/estudio/posts'
    | '/estudio/tiers'
    | '/mensagens/$conversationId'
    | '/estudio/'
    | '/mensagens/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/explorar'
    | '/assinaturas'
    | '/carteira'
    | '/configuracoes'
    | '/feed'
    | '/c/$handle'
    | '/estudio/posts'
    | '/estudio/tiers'
    | '/mensagens/$conversationId'
    | '/estudio'
    | '/mensagens'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/explorar'
    | '/_authenticated/assinaturas'
    | '/_authenticated/carteira'
    | '/_authenticated/configuracoes'
    | '/_authenticated/estudio'
    | '/_authenticated/feed'
    | '/c/$handle'
    | '/_authenticated/estudio/posts'
    | '/_authenticated/estudio/tiers'
    | '/_authenticated/mensagens/$conversationId'
    | '/_authenticated/estudio/'
    | '/_authenticated/mensagens/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ExplorarRoute: typeof ExplorarRoute
  CHandleRoute: typeof CHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$handle': {
      id: '/c/$handle'
      path: '/c/$handle'
      fullPath: '/c/$handle'
      preLoaderRoute: typeof CHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/estudio': {
      id: '/_authenticated/estudio'
      path: '/estudio'
      fullPath: '/estudio'
      preLoaderRoute: typeof AuthenticatedEstudioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/carteira': {
      id: '/_authenticated/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof AuthenticatedCarteiraRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assinaturas': {
      id: '/_authenticated/assinaturas'
      path: '/assinaturas'
      fullPath: '/assinaturas'
      preLoaderRoute: typeof AuthenticatedAssinaturasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mensagens/': {
      id: '/_authenticated/mensagens/'
      path: '/mensagens'
      fullPath: '/mensagens/'
      preLoaderRoute: typeof AuthenticatedMensagensIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/estudio/': {
      id: '/_authenticated/estudio/'
      path: '/'
      fullPath: '/estudio/'
      preLoaderRoute: typeof AuthenticatedEstudioIndexRouteImport
      parentRoute: typeof AuthenticatedEstudioRoute
    }
    '/_authenticated/mensagens/$conversationId': {
      id: '/_authenticated/mensagens/$conversationId'
      path: '/mensagens/$conversationId'
      fullPath: '/mensagens/$conversationId'
      preLoaderRoute: typeof AuthenticatedMensagensConversationIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/estudio/tiers': {
      id: '/_authenticated/estudio/tiers'
      path: '/tiers'
      fullPath: '/estudio/tiers'
      preLoaderRoute: typeof AuthenticatedEstudioTiersRouteImport
      parentRoute: typeof AuthenticatedEstudioRoute
    }
    '/_authenticated/estudio/posts': {
      id: '/_authenticated/estudio/posts'
      path: '/posts'
      fullPath: '/estudio/posts'
      preLoaderRoute: typeof AuthenticatedEstudioPostsRouteImport
      parentRoute: typeof AuthenticatedEstudioRoute
    }
  }
}

interface AuthenticatedEstudioRouteChildren {
  AuthenticatedEstudioPostsRoute: typeof AuthenticatedEstudioPostsRoute
  AuthenticatedEstudioTiersRoute: typeof AuthenticatedEstudioTiersRoute
  AuthenticatedEstudioIndexRoute: typeof AuthenticatedEstudioIndexRoute
}

const AuthenticatedEstudioRouteChildren: AuthenticatedEstudioRouteChildren = {
  AuthenticatedEstudioPostsRoute: AuthenticatedEstudioPostsRoute,
  AuthenticatedEstudioTiersRoute: AuthenticatedEstudioTiersRoute,
  AuthenticatedEstudioIndexRoute: AuthenticatedEstudioIndexRoute,
}

const AuthenticatedEstudioRouteWithChildren =
  AuthenticatedEstudioRoute._addFileChildren(AuthenticatedEstudioRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAssinaturasRoute: typeof AuthenticatedAssinaturasRoute
  AuthenticatedCarteiraRoute: typeof AuthenticatedCarteiraRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedEstudioRoute: typeof AuthenticatedEstudioRouteWithChildren
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedMensagensConversationIdRoute: typeof AuthenticatedMensagensConversationIdRoute
  AuthenticatedMensagensIndexRoute: typeof AuthenticatedMensagensIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAssinaturasRoute: AuthenticatedAssinaturasRoute,
  AuthenticatedCarteiraRoute: AuthenticatedCarteiraRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedEstudioRoute: AuthenticatedEstudioRouteWithChildren,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedMensagensConversationIdRoute:
    AuthenticatedMensagensConversationIdRoute,
  AuthenticatedMensagensIndexRoute: AuthenticatedMensagensIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ExplorarRoute: ExplorarRoute,
  CHandleRoute: CHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
